source:
  rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
keys:
  - suitcase
  - person
  - skateboard
street:
  xx街道
title:
  通道处有杂物摆放
category:
  通道阻塞
interval:
  10
device:
  cpu
report_url:
  https://longgang.yoyoyard.com/api/v1/events